SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [MERGEPROCESS_New].[PreMerge]
	AS 
Declare @LogDate datetime = (Select getdate())

INSERT INTO MERGEPROCESS_New.LogPreMergeAccount
(
	FK_MergeID
	,ObjectType
	,MergeRecordType
	,LogDate
	,Id
	,IsDeleted
	,MasterRecordId
	,Name
	,LastName
	,FirstName
	,Salutation
	,Type
	,RecordTypeId
	,ParentId
	,BillingStreet
	,BillingCity
	,BillingState
	,BillingPostalCode
	,BillingCountry
	,BillingLatitude
	,BillingLongitude
	,BillingGeocodeAccuracy
	,BillingAddress
	,ShippingStreet
	,ShippingCity
	,ShippingState
	,ShippingPostalCode
	,ShippingCountry
	,ShippingLatitude
	,ShippingLongitude
	,ShippingGeocodeAccuracy
	,ShippingAddress
	,Phone
	,Fax
	,AccountNumber
	,Website
	,PhotoUrl
	,Industry
	,AnnualRevenue
	,NumberOfEmployees
	,Description
	,OwnerId
	,CreatedDate
	,CreatedById
	,LastModifiedDate
	,LastModifiedById
	,SystemModstamp
	,LastActivityDate
	,LastViewedDate
	,LastReferencedDate
	,PersonContactId
	,IsPersonAccount
	,PersonMailingStreet
	,PersonMailingCity
	,PersonMailingState
	,PersonMailingPostalCode
	,PersonMailingCountry
	,PersonMailingLatitude
	,PersonMailingLongitude
	,PersonMailingGeocodeAccuracy
	,PersonMailingAddress
	,PersonOtherStreet
	,PersonOtherCity
	,PersonOtherState
	,PersonOtherPostalCode
	,PersonOtherCountry
	,PersonOtherLatitude
	,PersonOtherLongitude
	,PersonOtherGeocodeAccuracy
	,PersonOtherAddress
	,PersonMobilePhone
	,PersonHomePhone
	,PersonOtherPhone
	,PersonAssistantPhone
	,PersonEmail
	,PersonTitle
	,PersonDepartment
	,PersonAssistantName
	,PersonLeadSource
	,PersonBirthdate
	,PersonLastCURequestDate
	,PersonLastCUUpdateDate
	,PersonEmailBouncedReason
	,PersonEmailBouncedDate
	,Jigsaw
	,JigsawCompanyId
	,AccountSource
	,DunsNumber
	,Tradestyle
	,NaicsCode
	,NaicsDesc
	,YearStarted
	,SicDesc
	,SU_ID__c
	,Stanford_Alumni__c
	,Stanford_Grad_Year__c
	,Stanford_Degree__c
	,Assumed_Age__c
	,Gender__c
	,Income_Survey__c
	,Age_Survey__c
	,Family_Status_Survey__c
	,Stanford_Affiliate_Survey__c
	,City_State_ZIP__c
	,Import_List__c
	,Zip_Survey__c
	,iv__InsideView_Created__c
	,iv__InsideView_Date_Last_Updated__c
	,iv__InsideView_User_Last_Updated__c
	,Other_Handling_Instructions__c
	,Do_Not_Call__c
	,Do_Not_Email__c
	,Paciolan_Mark_Code__c
	,Not_Interested__c
	,Football_Priority_Seats__c
	,Comments__c
	,Industry__c
	,Biz_Other_Phone__c
	,Full_Account_ID__c
	,Business_Email__c
	,Employer__c
	,Paciolan_ID__c
	,Reasons_Why_Bought__c
	,F14_FS__c
	,F14_Partial__c
	,Men_s_Basketball_STM__c
	,Men_s_Basketball_Partial__c
	,F15_ERENEW__c
	,Women_s_Basketball_Partial__c
	,Baseball_STM__c
	,Baseball_Partial__c
	,Soccer_Full__c
	,Soccer_Partial__c
	,Donor_Flag__c
	,Donor_Warning__c
	,X2014_Football_Deposit__c
	,Price_Level__c
	,Football_Section__c
	,Football_Season_Seat_Blocks__c
	,Football_Row__c
	,Football_Total_Number_of_Seats__c
	,Customer_Type__c
	,Football_Season_Price_Type__c
	,Football_Years_as_STH__c
	,F14_GS__c
	,Football_Relocation_Request__c
	,Season_Purchase_Yesterday__c
	,Do_Not_Call_Warning__c
	,Former_Student_Athlete__c
	,Academic_Major__c
	,Name_on_PostGrads_Account__c
	,F13_FS__c
	,F13_GS__c
	,F13_Partial__c
	,F14_Single_Presale_Tier__c
	,StubHub_Account__c
	,StubHub_Account_Warning__c
	,Game_Days__c
	,Youth_League__c
	,Youth_Basketball_Team__c
	,F14_Games_Scanned_Pac__c
	,F14_Games_Attended_Survey__c
	,Attends_with_Friends__c
	,Attends_with_Family_Children_Under_18__c
	,Attends_with_Family_18__c
	,Attends_with_Groups__c
	,Attends_Alone__c
	,Attends_with_Other__c
	,Attends_with_Colleagues_Clients__c
	,Drives_to_Games__c
	,Likelihood_to_Park_in_STH_Only_Lot_1_5__c
	,Prefers_to_be_Contacted_by_Phone__c
	,Prefers_to_be_Contacted_by_Email__c
	,Prefers_to_be_Contacted_by_Mail__c
	,Likelihood_to_Renew_0_10__c
	,Reason_s_May_Not_Renew__c
	,Likelihood_to_Recommend_0_10__c
	,Alumnus_a__c
	,Family_of_Alumnus_a__c
	,Faculty_Staff__c
	,SAA_Member__c
	,Current_Student__c
	,Former_Student_Athlete_F14_Survey__c
	,Other_Stanford_Affiliation__c
	,Family_of_Faculty_Staff__c
	,Baseball_Fan__c
	,Buck_Cardinal_Club_Member__c
	,Interested_in_Buck_Cardinal_Club__c
	,Age__c
	,Family_Status__c
	,Profession__c
	,Family_of_Current_Student__c
	,Dropped_Seats_for_F14__c
	,Dropped_Seats_for_F14_Warning__c
	,F15_Renewal_Relocation_Add_On_Request__c
	,F15_Renewal_Comments__c
	,Known_Broker__c
	,Likely_Broker__c
	,Possible_Broker__c
	,Known_Broker_Flag__c
	,Likely_Broker_Flag__c
	,Possible_Broker_Flag__c
	,B14_Games_Attended__c
	,Football_STM__c
	,Women_s_Basketball_STM__c
	,B14_Freshman_STH__c
	,Service_Owner__c
	,Unique_ID__c
	,School_Level__c
	,School_Type__c
	,School_District__c
	,City__c
	,Previous_Educator_Day_Attendance__c
	,School_Enrollment__c
	,Previous_Relationship__c
	,School_Notes__c
	,Broker_Status__c
	,Broker_Status_Flag__c
	,F15_Single_Game_Presale_Tier__c
	,Connected_on_LinkedIn__c
	,dialforce__DS_Date_of_Last_Dispo__c
	,dialforce__DS_Last_Disposition__c
	,dialforce__DS_Total_Call_Count__c
	,Football_Partial__c
	,Men_s_Soccer_Partial__c
	,Women_s_Soccer_Partial__c
	,DS_Date_of_Last_Dispo__c
	,DS_Last_Disposition__c
	,DS_Total_Call_Count__c
	,F15_Renewal_Special_Handling__c
	,V15_Renewal_Special_Handling__c
	,Women_s_Volleyball_STM__c
	,Men_s_Soccer_STM__c
	,Women_s_Soccer_STM__c
	,Volleyball_Partial__c
	,Twitter_Account__c
	,Facebook_Account__c
	,Unlinked_eVenue_Account__c
	,eVenue_PIN__c
	,F16_Easy_Renew_Payment_Plan__c
	,iProfile__c
	,Priority_Seat_Gift_Amount__c
	,Priority_Seat_Gift_Received__c
	,Priority_Seat_Gift_Balance__c
	,Permanent_DNC__c
	,DS_Preferred_Phone__c
	,Auto_EM_Count__c
	,Personal_EM_Count__c
	,Total_EM_Count__c
	,Paciolan_pURL__c
	,Account_Merge_ID__c
	,Account_Merge_Master__c
	,B16_PURL__c
	,W16_PURL__c
	,DialSource__Date_of_Last_Disposition_DS__c
	,DialSource__Last_Disposition_DS__c
	,DialSource__Total_Call_Count_DS__c
	,DialSource__Next_Call_DS__c
	,DialSource__Datetime_of_Last_Disposition_DS__c
	,F16_Mini_Plan_Postcard__c
	,F16_Family_Plan_Postcard__c
	,SSB_CRMSYSTEM_Current_Student__c
	,SSB_CRMSYSTEM_Student_Partner__c
	,SSB_CRMSYSTEM_Stanford_Alumni__c
	,SSB_CRMSYSTEM_Block_S_Member__c
	,SSB_CRMSYSTEM_Faculty_Staff_Member__c
	,SSB_CRMSYSTEM_Daper_Staff__c
	,SSB_CRMSYSTEM_Daper_Retiree__c
	,SSB_CRMSYSTEM_SSID_Winner__c
	,SSB_CRMSYSTEM_SSID_Paciolan__c
	,SSB_CRMSYSTEM_VIP_Message__c
	,SSB_CRMSYSTEM_Broker_Flag__c
	,SSB_CRMSYSTEM_Opponent_Flag__c
	,SSB_CRMSYSTEM_HouseAccount_Flag__c
	,SSB_CRMSYSTEM_Visitor_Flag__c
	,SSB_CRMSYSTEM_Secondary_Patron__c
	,SSB_CRMSYSTEM_Contact_ID__c
	,iv__InsideView_Created__pc
	,iv__InsideView_Date_Last_Updated__pc
	,iv__InsideView_User_Last_Updated__pc
	,Gender__pc
	,Stanford_Alumni__pc
	,Stanford_Degree__pc
	,Stanford_Grad_Year__pc
	,SU_ID__pc
	,Inactive__pc
	,Secondary_Email__pc
	,Stanford_Student_Athlete__pc
	,Full_Contact_ID__pc
	,Preferred_Name__pc
	,Stanford_Alum_Spouse__pc
	,Stanford_Degree_Spouse__pc
	,Stanford_Grad_Year_Spouse__pc
	,Stanford_Student_Athlete_Spouse__pc
	,Adobe_Unsubscribe__pc
	,Email_Quarantine__pc
	,Email_Quarantine_Reason__pc
	,Email_Verified__pc
	,dialforce__DS_Date_of_Last_Dispo__pc
	,dialforce__DS_Last_Disposition__pc
	,dialforce__DS_Total_Call_Count__pc
	,Business_Phone__pc
	,Preferred_Phone__pc
	,Cell_Phone__pc
	,DS_Date_of_Last_Dispo__pc
	,DS_Last_Disposition__pc
	,DS_Total_Call_Count__pc
	,eVenue_Email_Address__pc
	,TEST__pc
	,PostGrads_ID__pc
	,DialSource__Date_of_Last_Disposition_DS__pc
	,DialSource__Last_Disposition_DS__pc
	,DialSource__Total_Call_Count_DS__pc
	,DialSource__Next_Call_DS__pc
	,DialSource__Datetime_of_Last_Disposition_DS__pc
	,CopyLoadDate
)
Select a.FK_MergeID,ObjectType, 'Winning' MergeRecordType, @LogDate LogDate
	,Id
	,IsDeleted
	,MasterRecordId
	,Name
	,LastName
	,FirstName
	,Salutation
	,Type
	,RecordTypeId
	,ParentId
	,BillingStreet
	,BillingCity
	,BillingState
	,BillingPostalCode
	,BillingCountry
	,BillingLatitude
	,BillingLongitude
	,BillingGeocodeAccuracy
	,BillingAddress
	,ShippingStreet
	,ShippingCity
	,ShippingState
	,ShippingPostalCode
	,ShippingCountry
	,ShippingLatitude
	,ShippingLongitude
	,ShippingGeocodeAccuracy
	,ShippingAddress
	,Phone
	,Fax
	,AccountNumber
	,Website
	,PhotoUrl
	,Industry
	,AnnualRevenue
	,NumberOfEmployees
	,Description
	,OwnerId
	,CreatedDate
	,CreatedById
	,LastModifiedDate
	,LastModifiedById
	,SystemModstamp
	,LastActivityDate
	,LastViewedDate
	,LastReferencedDate
	,PersonContactId
	,IsPersonAccount
	,PersonMailingStreet
	,PersonMailingCity
	,PersonMailingState
	,PersonMailingPostalCode
	,PersonMailingCountry
	,PersonMailingLatitude
	,PersonMailingLongitude
	,PersonMailingGeocodeAccuracy
	,PersonMailingAddress
	,PersonOtherStreet
	,PersonOtherCity
	,PersonOtherState
	,PersonOtherPostalCode
	,PersonOtherCountry
	,PersonOtherLatitude
	,PersonOtherLongitude
	,PersonOtherGeocodeAccuracy
	,PersonOtherAddress
	,PersonMobilePhone
	,PersonHomePhone
	,PersonOtherPhone
	,PersonAssistantPhone
	,PersonEmail
	,PersonTitle
	,PersonDepartment
	,PersonAssistantName
	,PersonLeadSource
	,PersonBirthdate
	,PersonLastCURequestDate
	,PersonLastCUUpdateDate
	,PersonEmailBouncedReason
	,PersonEmailBouncedDate
	,Jigsaw
	,JigsawCompanyId
	,AccountSource
	,DunsNumber
	,Tradestyle
	,NaicsCode
	,NaicsDesc
	,YearStarted
	,SicDesc
	,SU_ID__c
	,Stanford_Alumni__c
	,Stanford_Grad_Year__c
	,Stanford_Degree__c
	,Assumed_Age__c
	,Gender__c
	,Income_Survey__c
	,Age_Survey__c
	,Family_Status_Survey__c
	,Stanford_Affiliate_Survey__c
	,City_State_ZIP__c
	,Import_List__c
	,Zip_Survey__c
	,iv__InsideView_Created__c
	,iv__InsideView_Date_Last_Updated__c
	,iv__InsideView_User_Last_Updated__c
	,Other_Handling_Instructions__c
	,Do_Not_Call__c
	,Do_Not_Email__c
	,Paciolan_Mark_Code__c
	,Not_Interested__c
	,Football_Priority_Seats__c
	,Comments__c
	,Industry__c
	,Biz_Other_Phone__c
	,Full_Account_ID__c
	,Business_Email__c
	,Employer__c
	,Paciolan_ID__c
	,Reasons_Why_Bought__c
	,F14_FS__c
	,F14_Partial__c
	,Men_s_Basketball_STM__c
	,Men_s_Basketball_Partial__c
	,F15_ERENEW__c
	,Women_s_Basketball_Partial__c
	,Baseball_STM__c
	,Baseball_Partial__c
	,Soccer_Full__c
	,Soccer_Partial__c
	,Donor_Flag__c
	,Donor_Warning__c
	,X2014_Football_Deposit__c
	,Price_Level__c
	,Football_Section__c
	,Football_Season_Seat_Blocks__c
	,Football_Row__c
	,Football_Total_Number_of_Seats__c
	,Customer_Type__c
	,Football_Season_Price_Type__c
	,Football_Years_as_STH__c
	,F14_GS__c
	,Football_Relocation_Request__c
	,Season_Purchase_Yesterday__c
	,Do_Not_Call_Warning__c
	,Former_Student_Athlete__c
	,Academic_Major__c
	,Name_on_PostGrads_Account__c
	,F13_FS__c
	,F13_GS__c
	,F13_Partial__c
	,F14_Single_Presale_Tier__c
	,StubHub_Account__c
	,StubHub_Account_Warning__c
	,Game_Days__c
	,Youth_League__c
	,Youth_Basketball_Team__c
	,F14_Games_Scanned_Pac__c
	,F14_Games_Attended_Survey__c
	,Attends_with_Friends__c
	,Attends_with_Family_Children_Under_18__c
	,Attends_with_Family_18__c
	,Attends_with_Groups__c
	,Attends_Alone__c
	,Attends_with_Other__c
	,Attends_with_Colleagues_Clients__c
	,Drives_to_Games__c
	,Likelihood_to_Park_in_STH_Only_Lot_1_5__c
	,Prefers_to_be_Contacted_by_Phone__c
	,Prefers_to_be_Contacted_by_Email__c
	,Prefers_to_be_Contacted_by_Mail__c
	,Likelihood_to_Renew_0_10__c
	,Reason_s_May_Not_Renew__c
	,Likelihood_to_Recommend_0_10__c
	,Alumnus_a__c
	,Family_of_Alumnus_a__c
	,Faculty_Staff__c
	,SAA_Member__c
	,Current_Student__c
	,Former_Student_Athlete_F14_Survey__c
	,Other_Stanford_Affiliation__c
	,Family_of_Faculty_Staff__c
	,Baseball_Fan__c
	,Buck_Cardinal_Club_Member__c
	,Interested_in_Buck_Cardinal_Club__c
	,Age__c
	,Family_Status__c
	,Profession__c
	,Family_of_Current_Student__c
	,Dropped_Seats_for_F14__c
	,Dropped_Seats_for_F14_Warning__c
	,F15_Renewal_Relocation_Add_On_Request__c
	,F15_Renewal_Comments__c
	,Known_Broker__c
	,Likely_Broker__c
	,Possible_Broker__c
	,Known_Broker_Flag__c
	,Likely_Broker_Flag__c
	,Possible_Broker_Flag__c
	,B14_Games_Attended__c
	,Football_STM__c
	,Women_s_Basketball_STM__c
	,B14_Freshman_STH__c
	,Service_Owner__c
	,Unique_ID__c
	,School_Level__c
	,School_Type__c
	,School_District__c
	,City__c
	,Previous_Educator_Day_Attendance__c
	,School_Enrollment__c
	,Previous_Relationship__c
	,School_Notes__c
	,Broker_Status__c
	,Broker_Status_Flag__c
	,F15_Single_Game_Presale_Tier__c
	,Connected_on_LinkedIn__c
	,dialforce__DS_Date_of_Last_Dispo__c
	,dialforce__DS_Last_Disposition__c
	,dialforce__DS_Total_Call_Count__c
	,Football_Partial__c
	,Men_s_Soccer_Partial__c
	,Women_s_Soccer_Partial__c
	,DS_Date_of_Last_Dispo__c
	,DS_Last_Disposition__c
	,DS_Total_Call_Count__c
	,F15_Renewal_Special_Handling__c
	,V15_Renewal_Special_Handling__c
	,Women_s_Volleyball_STM__c
	,Men_s_Soccer_STM__c
	,Women_s_Soccer_STM__c
	,Volleyball_Partial__c
	,Twitter_Account__c
	,Facebook_Account__c
	,Unlinked_eVenue_Account__c
	,eVenue_PIN__c
	,F16_Easy_Renew_Payment_Plan__c
	,iProfile__c
	,Priority_Seat_Gift_Amount__c
	,Priority_Seat_Gift_Received__c
	,Priority_Seat_Gift_Balance__c
	,Permanent_DNC__c
	,DS_Preferred_Phone__c
	,Auto_EM_Count__c
	,Personal_EM_Count__c
	,Total_EM_Count__c
	,Paciolan_pURL__c
	,Account_Merge_ID__c
	,Account_Merge_Master__c
	,B16_PURL__c
	,W16_PURL__c
	,DialSource__Date_of_Last_Disposition_DS__c
	,DialSource__Last_Disposition_DS__c
	,DialSource__Total_Call_Count_DS__c
	,DialSource__Next_Call_DS__c
	,DialSource__Datetime_of_Last_Disposition_DS__c
	,F16_Mini_Plan_Postcard__c
	,F16_Family_Plan_Postcard__c
	,SSB_CRMSYSTEM_Current_Student__c
	,SSB_CRMSYSTEM_Student_Partner__c
	,SSB_CRMSYSTEM_Stanford_Alumni__c
	,SSB_CRMSYSTEM_Block_S_Member__c
	,SSB_CRMSYSTEM_Faculty_Staff_Member__c
	,SSB_CRMSYSTEM_Daper_Staff__c
	,SSB_CRMSYSTEM_Daper_Retiree__c
	,SSB_CRMSYSTEM_SSID_Winner__c
	,SSB_CRMSYSTEM_SSID_Paciolan__c
	,SSB_CRMSYSTEM_VIP_Message__c
	,SSB_CRMSYSTEM_Broker_Flag__c
	,SSB_CRMSYSTEM_Opponent_Flag__c
	,SSB_CRMSYSTEM_HouseAccount_Flag__c
	,SSB_CRMSYSTEM_Visitor_Flag__c
	,SSB_CRMSYSTEM_Secondary_Patron__c
	,SSB_CRMSYSTEM_Contact_ID__c
	,iv__InsideView_Created__pc
	,iv__InsideView_Date_Last_Updated__pc
	,iv__InsideView_User_Last_Updated__pc
	,Gender__pc
	,Stanford_Alumni__pc
	,Stanford_Degree__pc
	,Stanford_Grad_Year__pc
	,SU_ID__pc
	,Inactive__pc
	,Secondary_Email__pc
	,Stanford_Student_Athlete__pc
	,Full_Contact_ID__pc
	,Preferred_Name__pc
	,Stanford_Alum_Spouse__pc
	,Stanford_Degree_Spouse__pc
	,Stanford_Grad_Year_Spouse__pc
	,Stanford_Student_Athlete_Spouse__pc
	,Adobe_Unsubscribe__pc
	,Email_Quarantine__pc
	,Email_Quarantine_Reason__pc
	,Email_Verified__pc
	,dialforce__DS_Date_of_Last_Dispo__pc
	,dialforce__DS_Last_Disposition__pc
	,dialforce__DS_Total_Call_Count__pc
	,Business_Phone__pc
	,Preferred_Phone__pc
	,Cell_Phone__pc
	,DS_Date_of_Last_Dispo__pc
	,DS_Last_Disposition__pc
	,DS_Total_Call_Count__pc
	,eVenue_Email_Address__pc
	,TEST__pc
	,PostGrads_ID__pc
	,DialSource__Date_of_Last_Disposition_DS__pc
	,DialSource__Last_Disposition_DS__pc
	,DialSource__Total_Call_Count_DS__pc
	,DialSource__Next_Call_DS__pc
	,DialSource__Datetime_of_Last_Disposition_DS__pc
	,CopyLoadDate
FROM MERGEPROCESS_New.Queue a with (nolock)
JOIN mergeprocess_new.tmp_pcaccount b with (nolock)
	ON a.Winning_ID = b.ID
UNION ALL
Select a.FK_MergeID,ObjectType, 'Losing' MergeRecordType, @LogDate LogDate
	,Id
	,IsDeleted
	,MasterRecordId
	,Name
	,LastName
	,FirstName
	,Salutation
	,Type
	,RecordTypeId
	,ParentId
	,BillingStreet
	,BillingCity
	,BillingState
	,BillingPostalCode
	,BillingCountry
	,BillingLatitude
	,BillingLongitude
	,BillingGeocodeAccuracy
	,BillingAddress
	,ShippingStreet
	,ShippingCity
	,ShippingState
	,ShippingPostalCode
	,ShippingCountry
	,ShippingLatitude
	,ShippingLongitude
	,ShippingGeocodeAccuracy
	,ShippingAddress
	,Phone
	,Fax
	,AccountNumber
	,Website
	,PhotoUrl
	,Industry
	,AnnualRevenue
	,NumberOfEmployees
	,Description
	,OwnerId
	,CreatedDate
	,CreatedById
	,LastModifiedDate
	,LastModifiedById
	,SystemModstamp
	,LastActivityDate
	,LastViewedDate
	,LastReferencedDate
	,PersonContactId
	,IsPersonAccount
	,PersonMailingStreet
	,PersonMailingCity
	,PersonMailingState
	,PersonMailingPostalCode
	,PersonMailingCountry
	,PersonMailingLatitude
	,PersonMailingLongitude
	,PersonMailingGeocodeAccuracy
	,PersonMailingAddress
	,PersonOtherStreet
	,PersonOtherCity
	,PersonOtherState
	,PersonOtherPostalCode
	,PersonOtherCountry
	,PersonOtherLatitude
	,PersonOtherLongitude
	,PersonOtherGeocodeAccuracy
	,PersonOtherAddress
	,PersonMobilePhone
	,PersonHomePhone
	,PersonOtherPhone
	,PersonAssistantPhone
	,PersonEmail
	,PersonTitle
	,PersonDepartment
	,PersonAssistantName
	,PersonLeadSource
	,PersonBirthdate
	,PersonLastCURequestDate
	,PersonLastCUUpdateDate
	,PersonEmailBouncedReason
	,PersonEmailBouncedDate
	,Jigsaw
	,JigsawCompanyId
	,AccountSource
	,DunsNumber
	,Tradestyle
	,NaicsCode
	,NaicsDesc
	,YearStarted
	,SicDesc
	,SU_ID__c
	,Stanford_Alumni__c
	,Stanford_Grad_Year__c
	,Stanford_Degree__c
	,Assumed_Age__c
	,Gender__c
	,Income_Survey__c
	,Age_Survey__c
	,Family_Status_Survey__c
	,Stanford_Affiliate_Survey__c
	,City_State_ZIP__c
	,Import_List__c
	,Zip_Survey__c
	,iv__InsideView_Created__c
	,iv__InsideView_Date_Last_Updated__c
	,iv__InsideView_User_Last_Updated__c
	,Other_Handling_Instructions__c
	,Do_Not_Call__c
	,Do_Not_Email__c
	,Paciolan_Mark_Code__c
	,Not_Interested__c
	,Football_Priority_Seats__c
	,Comments__c
	,Industry__c
	,Biz_Other_Phone__c
	,Full_Account_ID__c
	,Business_Email__c
	,Employer__c
	,Paciolan_ID__c
	,Reasons_Why_Bought__c
	,F14_FS__c
	,F14_Partial__c
	,Men_s_Basketball_STM__c
	,Men_s_Basketball_Partial__c
	,F15_ERENEW__c
	,Women_s_Basketball_Partial__c
	,Baseball_STM__c
	,Baseball_Partial__c
	,Soccer_Full__c
	,Soccer_Partial__c
	,Donor_Flag__c
	,Donor_Warning__c
	,X2014_Football_Deposit__c
	,Price_Level__c
	,Football_Section__c
	,Football_Season_Seat_Blocks__c
	,Football_Row__c
	,Football_Total_Number_of_Seats__c
	,Customer_Type__c
	,Football_Season_Price_Type__c
	,Football_Years_as_STH__c
	,F14_GS__c
	,Football_Relocation_Request__c
	,Season_Purchase_Yesterday__c
	,Do_Not_Call_Warning__c
	,Former_Student_Athlete__c
	,Academic_Major__c
	,Name_on_PostGrads_Account__c
	,F13_FS__c
	,F13_GS__c
	,F13_Partial__c
	,F14_Single_Presale_Tier__c
	,StubHub_Account__c
	,StubHub_Account_Warning__c
	,Game_Days__c
	,Youth_League__c
	,Youth_Basketball_Team__c
	,F14_Games_Scanned_Pac__c
	,F14_Games_Attended_Survey__c
	,Attends_with_Friends__c
	,Attends_with_Family_Children_Under_18__c
	,Attends_with_Family_18__c
	,Attends_with_Groups__c
	,Attends_Alone__c
	,Attends_with_Other__c
	,Attends_with_Colleagues_Clients__c
	,Drives_to_Games__c
	,Likelihood_to_Park_in_STH_Only_Lot_1_5__c
	,Prefers_to_be_Contacted_by_Phone__c
	,Prefers_to_be_Contacted_by_Email__c
	,Prefers_to_be_Contacted_by_Mail__c
	,Likelihood_to_Renew_0_10__c
	,Reason_s_May_Not_Renew__c
	,Likelihood_to_Recommend_0_10__c
	,Alumnus_a__c
	,Family_of_Alumnus_a__c
	,Faculty_Staff__c
	,SAA_Member__c
	,Current_Student__c
	,Former_Student_Athlete_F14_Survey__c
	,Other_Stanford_Affiliation__c
	,Family_of_Faculty_Staff__c
	,Baseball_Fan__c
	,Buck_Cardinal_Club_Member__c
	,Interested_in_Buck_Cardinal_Club__c
	,Age__c
	,Family_Status__c
	,Profession__c
	,Family_of_Current_Student__c
	,Dropped_Seats_for_F14__c
	,Dropped_Seats_for_F14_Warning__c
	,F15_Renewal_Relocation_Add_On_Request__c
	,F15_Renewal_Comments__c
	,Known_Broker__c
	,Likely_Broker__c
	,Possible_Broker__c
	,Known_Broker_Flag__c
	,Likely_Broker_Flag__c
	,Possible_Broker_Flag__c
	,B14_Games_Attended__c
	,Football_STM__c
	,Women_s_Basketball_STM__c
	,B14_Freshman_STH__c
	,Service_Owner__c
	,Unique_ID__c
	,School_Level__c
	,School_Type__c
	,School_District__c
	,City__c
	,Previous_Educator_Day_Attendance__c
	,School_Enrollment__c
	,Previous_Relationship__c
	,School_Notes__c
	,Broker_Status__c
	,Broker_Status_Flag__c
	,F15_Single_Game_Presale_Tier__c
	,Connected_on_LinkedIn__c
	,dialforce__DS_Date_of_Last_Dispo__c
	,dialforce__DS_Last_Disposition__c
	,dialforce__DS_Total_Call_Count__c
	,Football_Partial__c
	,Men_s_Soccer_Partial__c
	,Women_s_Soccer_Partial__c
	,DS_Date_of_Last_Dispo__c
	,DS_Last_Disposition__c
	,DS_Total_Call_Count__c
	,F15_Renewal_Special_Handling__c
	,V15_Renewal_Special_Handling__c
	,Women_s_Volleyball_STM__c
	,Men_s_Soccer_STM__c
	,Women_s_Soccer_STM__c
	,Volleyball_Partial__c
	,Twitter_Account__c
	,Facebook_Account__c
	,Unlinked_eVenue_Account__c
	,eVenue_PIN__c
	,F16_Easy_Renew_Payment_Plan__c
	,iProfile__c
	,Priority_Seat_Gift_Amount__c
	,Priority_Seat_Gift_Received__c
	,Priority_Seat_Gift_Balance__c
	,Permanent_DNC__c
	,DS_Preferred_Phone__c
	,Auto_EM_Count__c
	,Personal_EM_Count__c
	,Total_EM_Count__c
	,Paciolan_pURL__c
	,Account_Merge_ID__c
	,Account_Merge_Master__c
	,B16_PURL__c
	,W16_PURL__c
	,DialSource__Date_of_Last_Disposition_DS__c
	,DialSource__Last_Disposition_DS__c
	,DialSource__Total_Call_Count_DS__c
	,DialSource__Next_Call_DS__c
	,DialSource__Datetime_of_Last_Disposition_DS__c
	,F16_Mini_Plan_Postcard__c
	,F16_Family_Plan_Postcard__c
	,SSB_CRMSYSTEM_Current_Student__c
	,SSB_CRMSYSTEM_Student_Partner__c
	,SSB_CRMSYSTEM_Stanford_Alumni__c
	,SSB_CRMSYSTEM_Block_S_Member__c
	,SSB_CRMSYSTEM_Faculty_Staff_Member__c
	,SSB_CRMSYSTEM_Daper_Staff__c
	,SSB_CRMSYSTEM_Daper_Retiree__c
	,SSB_CRMSYSTEM_SSID_Winner__c
	,SSB_CRMSYSTEM_SSID_Paciolan__c
	,SSB_CRMSYSTEM_VIP_Message__c
	,SSB_CRMSYSTEM_Broker_Flag__c
	,SSB_CRMSYSTEM_Opponent_Flag__c
	,SSB_CRMSYSTEM_HouseAccount_Flag__c
	,SSB_CRMSYSTEM_Visitor_Flag__c
	,SSB_CRMSYSTEM_Secondary_Patron__c
	,SSB_CRMSYSTEM_Contact_ID__c
	,iv__InsideView_Created__pc
	,iv__InsideView_Date_Last_Updated__pc
	,iv__InsideView_User_Last_Updated__pc
	,Gender__pc
	,Stanford_Alumni__pc
	,Stanford_Degree__pc
	,Stanford_Grad_Year__pc
	,SU_ID__pc
	,Inactive__pc
	,Secondary_Email__pc
	,Stanford_Student_Athlete__pc
	,Full_Contact_ID__pc
	,Preferred_Name__pc
	,Stanford_Alum_Spouse__pc
	,Stanford_Degree_Spouse__pc
	,Stanford_Grad_Year_Spouse__pc
	,Stanford_Student_Athlete_Spouse__pc
	,Adobe_Unsubscribe__pc
	,Email_Quarantine__pc
	,Email_Quarantine_Reason__pc
	,Email_Verified__pc
	,dialforce__DS_Date_of_Last_Dispo__pc
	,dialforce__DS_Last_Disposition__pc
	,dialforce__DS_Total_Call_Count__pc
	,Business_Phone__pc
	,Preferred_Phone__pc
	,Cell_Phone__pc
	,DS_Date_of_Last_Dispo__pc
	,DS_Last_Disposition__pc
	,DS_Total_Call_Count__pc
	,eVenue_Email_Address__pc
	,TEST__pc
	,PostGrads_ID__pc
	,DialSource__Date_of_Last_Disposition_DS__pc
	,DialSource__Last_Disposition_DS__pc
	,DialSource__Total_Call_Count_DS__pc
	,DialSource__Next_Call_DS__pc
	,DialSource__Datetime_of_Last_Disposition_DS__pc
	,CopyLoadDate
FROM MERGEPROCESS_New.Queue a with (nolock)
JOIN mergeprocess_new.tmp_pcaccount b with (nolock)
	ON a.Losing_ID = b.ID

--INSERT INTO MERGEPROCESS_New.LogPreMergeContact
--Select a.FK_MergeID,ObjectType, 'Winning' MergeRecordType, @LogDate LogDate, b.*
--FROM MERGEPROCESS_New.Queue a
--JOIN Prodcopy.Contact b
--	ON a.Winning_ID = b.ID
--UNION ALL
--Select a.FK_MergeID,ObjectType, 'Losing' MergeRecordType, @LogDate LogDate, b.*
--FROM MERGEPROCESS_New.Queue a
--JOIN Prodcopy.Contact b
--	ON a.Losing_ID = b.ID

GO
