CREATE TABLE [dbo].[Contact_Custom_CRMResults]
(
[SSB_CRMSYSTEM_Contact_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRMProcess_UpdatedDate] [datetime] NULL,
[ErrorCode] [int] NULL,
[ErrorColumn] [int] NULL,
[Update SF Dest.Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ErrorDescription] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Person.Id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Paciolan__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Broker_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_Opponent_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_HouseAccount_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_Visitor_Flag__c] [bit] NULL,
[Twitter_Account__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facebook_Account__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football_STM__c] [bit] NULL,
[Men_s_Basketball_STM__c] [bit] NULL,
[Women_s_Basketball_STM__c] [bit] NULL,
[Women_s_Volleyball_STM__c] [bit] NULL,
[Women_s_Soccer_STM__c] [bit] NULL,
[Men_s_Soccer_STM__c] [bit] NULL,
[Baseball_STM__c] [bit] NULL,
[Football_Partial__c] [bit] NULL,
[Men_s_Basketball_Partial__c] [bit] NULL,
[Women_s_Basketball_Partial__c] [bit] NULL,
[Volleyball_Partial__c] [bit] NULL,
[Women_s_Soccer_Partial__c] [bit] NULL,
[Men_s_Soccer_Partial__c] [bit] NULL,
[Baseball_Partial__c] [bit] NULL,
[SSB_CRMSYSTEM_Current_Student__c] [bit] NULL,
[SSB_CRMSYSTEM_Student_Partner__c] [bit] NULL,
[SSB_CRMSYSTEM_Stanford_Alumni__c] [bit] NULL,
[SSB_CRMSYSTEM_Block_S_Member__c] [bit] NULL,
[SSB_CRMSYSTEM_Faculty_Staff_Member__c] [bit] NULL,
[SSB_CRMSYSTEM_Daper_Staff__c] [bit] NULL,
[SSB_CRMSYSTEM_Daper_Retiree__c] [bit] NULL,
[Comments__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_VIP_Message__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Secondary_Patron__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Organization_Type__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonMailingCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonEmail] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonHomePhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Email__c] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonBirthdate] [date] NULL
)
GO
