CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_Contact_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSID_Winner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TI_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonTicket_Years] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRMProcess_UpdatedDate] [datetime] NULL,
[SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c] [date] NULL,
[SSB_CRMSYSTEM_Broker_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_Opponent_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_HouseAccount_Flag__c] [bit] NULL,
[SSB_CRMSYSTEM_Visitor_Flag__c] [bit] NULL,
[Twitter_Account__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Facebook_Account__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football_STM__c] [bit] NULL,
[Men_s_Basketball_STM__c] [bit] NULL,
[Women_s_Basketball_STM__c] [bit] NULL,
[Women_s_Volleyball_STM__c] [bit] NULL,
[Women_s_Soccer_STM__c] [bit] NULL,
[Men_s_Soccer_STM__c] [bit] NULL,
[Baseball_STM__c] [bit] NULL,
[Football_Partial__c] [bit] NULL,
[Men_s_Basketball_Partial__c] [bit] NULL,
[Women_s_Basketball_Partial__c] [bit] NULL,
[Volleyball_Partial__c] [bit] NULL,
[Women_s_Soccer_Partial__c] [bit] NULL,
[Men_s_Soccer_Partial__c] [bit] NULL,
[Baseball_Partial__c] [bit] NULL,
[SSB_CRMSYSTEM_Current_Student__c] [bit] NULL,
[SSB_CRMSYSTEM_Student_Partner__c] [bit] NULL,
[SSB_CRMSYSTEM_Stanford_Alumni__c] [bit] NULL,
[SSB_CRMSYSTEM_Block_S_Member__c] [bit] NULL,
[SSB_CRMSYSTEM_Faculty_Staff_Member__c] [bit] NULL,
[SSB_CRMSYSTEM_Daper_Staff__c] [bit] NULL,
[SSB_CRMSYSTEM_Daper_Retiree__c] [bit] NULL,
[Comments__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_VIP_Message] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Quarantine__pc] [bit] NULL,
[Adobe_Unsubscribe__pc] [bit] NULL,
[Email_Quarantine_Reason__pc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Secondary_Patron__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonOtherPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonEmail] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Secondary_Email__pc] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred_Phone__pc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cell_Phone__pc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Phone__pc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonBirthdate] [date] NULL,
[AddressTwoStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressTwoCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressTwoState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressTwoZip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressTwoCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFourStreet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFourCity] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFourState] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFourZip] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressFourCountry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business_Email__c] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonHomePhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_Organization_Type__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FB_Loyal_group__c] [bit] NULL,
[MBB_Loyal_Group__c] [bit] NULL,
[Soccer_Loyal_Group__c] [bit] NULL,
[WBB_Loyal_Group__c] [bit] NULL,
[WVB_Loyal_Group__c] [bit] NULL,
[Baseball_Loyal_Group__c] [bit] NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_Contact_ID])
GO
